### ISSUE TITLE
Expansion board does not light LEDs

### ISSUE THREAD

**Issue by ironspider** [fastpinball/mpf#5]
Even though all the configs look correct, when in attract mode, a blinking LED attract show that does play when the LED is connected to the Neuron's LED headers, does not play when connected to the EXP board's header.

Here are the relevant sections:
```
#config.yaml
fast:
  net:
    port: com4
    controller: neuron
    io_loop:
            playfield_1616:
                model: FP-I/O-1616
                order: 1
    watchdog: 1s
  exp:
    port: com5
    boards: 
      neuron:
        model: FP-EXP-2000
        breakouts:
          #- port: 1
          #  model: FP-PWR-0007
      cabinet_exp:
        model: FP-EXP-0081
        id: 0
        led_ports:
          - port: 1
            leds: 32
            type: ws2812

lights:
  l_rgbw_test_1:
    number: cabinet_exp-1-1
    subtype: led
    type: rgb
  l_rgbw_test_2:
    number: cabinet_exp-1-2
    #previous: l_rgbw_test_1
    subtype: led
    type: rgb
```

```
#attract.yaml
show_player:
  mode_attract_started:
    led_test:
      speed: 1

shows:
  led_test:
    - duration: 3000ms
      lights:
        l_rgbw_test_1: red
        l_rgbw_test_2: red
    - duration: 1000ms
      lights:
        l_rgbw_test_1: off
        l_rgbw_test_2: off
```
