### ISSUE TITLE
Neuron error for breakout board - power filter

### ISSUE THREAD

**Issue by ironspider** [fastpinball/mpf#6]
FAST MPF dev7 crashes on launch with the error "Expected FP-PWR-0007 but got LED FP-BRK-0001  0.8 from FP-EXP-2000 "neuron"" when using the following code in the exp config section:

```
  exp:
    port: com5
    boards: 
      neuron:
        model: FP-EXP-2000
        breakouts:
          - port: 1
            model: FP-PWR-0007
```
